import {all,put,putMany,del,get,clear} from './core/db.js';
import {state,setState} from './core/state.js';
import {APP_VERSION,CREATOR,BUILD_DATE,esc,money,num,todayISO,uid,toast,parseCSV,normalizeKey} from './core/utils.js';
import {loadPricing,calcLine,saveTier,removeTier} from './modules/pricing.js';
import {newDraft,nextInvoiceNo,saveInvoice,autosaveInvoice,listInvoices,getInvoice,deleteInvoice} from './modules/invoices.js';
import {loadCatalog,saveSupplier,removeSupplier,saveItem,removeItem} from './modules/catalog.js';
import {getSettings,setSetting} from './modules/settings.js';
import {exportERP,exportCSV} from './modules/export.js';
import {printInvoice,shareImage} from './modules/receipt.js';
import {exportBackup,importBackup} from './modules/backup.js';

const app=document.getElementById('app');
const online=document.getElementById('onlineState');
document.getElementById('versionBadge').textContent=`v${APP_VERSION}`;
document.getElementById('creatorBadge').textContent=CREATOR;
document.getElementById('buildBadge').textContent=`Build ${BUILD_DATE}`;
function onlineUI(){online.textContent=navigator.onLine?'●':'○';online.title=navigator.onLine?'متصل بالإنترنت':'وضع محلي/بدون إنترنت';online.className=navigator.onLine?'online':'offline'}
onlineUI();addEventListener('online',onlineUI);addEventListener('offline',onlineUI);

const DEFAULT_ERP_COLUMNS=[
 {key:'seq',label:'المسلسل'},{key:'invoiceNo',label:'رقم الفاتورة'},{key:'date',label:'التاريخ'},{key:'supplier',label:'المورد'},
 {key:'supplierId',label:'كود المورد'},{key:'type',label:'النوع'},{key:'itemName',label:'اسم الصنف ERP'},{key:'itemId',label:'ID'},
 {key:'barcode',label:'الباركود'},{key:'lrp',label:'LRP'},{key:'lrb',label:'LRB'},{key:'qty',label:'الكمية بالقطعة'},
 {key:'unit',label:'الوحدة'},{key:'cartonQty',label:'كمية الدستة/الكرتونة'},{key:'purchasePrice',label:'سعر الشراء/قطعة'},
 {key:'cost',label:'التكلفة/قطعة'},{key:'purchaseCartonPrice',label:'سعر الشراء/الدستة أو الكرتونة'},
 {key:'sellPrice',label:'السعر بعد الخصم'},{key:'saleBeforeDiscount',label:'سعر البيع / قبل الخصم'},{key:'total',label:'الإجمالي'},{key:'profit',label:'الربح'},{key:'margin',label:'نسبة الربح'},{key:'notes',label:'ملاحظات'}
];
const IMPORT_FIELDS=[
 ['name','اسم الصنف'],['itemId','ID'],['barcode','الباركود'],['supplier','المورد'],['supplierCode','كود المورد'],['mainCategory','القسم الرئيسي'],['subCategory','القسم الفرعي'],['basePrice','السعر'],['salePriceBeforeDiscount','سعر البيع / قبل الخصم'],['salePriceAfterDiscount','السعر بعد الخصم'],['purchasePrice','سعر الشراء'],['cost','التكلفة'],['lrp','LRP'],['lrb','LRB']
];

async function migrateBlank(){
 const meta=await get('meta','seeded');
 if(meta?.source==='نموذج تسعير السليبر-1.xlsx' || meta?.source==='seed-v1.1.0'){
  await clear('suppliers');await clear('items');await clear('tiers');await del('meta','seeded');
  await put('meta',{id:'blankMigration',value:APP_VERSION,at:new Date().toISOString()});
 }
 await put('meta',{id:'appVersion',value:APP_VERSION});await put('meta',{id:'creator',value:CREATOR});await put('meta',{id:'buildDate',value:BUILD_DATE});
 if(!(await get('meta','erpColumns')))await put('meta',{id:'erpColumns',value:DEFAULT_ERP_COLUMNS});
 const s=await getSettings();
 if(s.marginRate==null)await setSetting('marginRate',0.35);
 if(!s.marginBasis)await setSetting('marginBasis','cost');
 if(!s.defaultType)await setSetting('defaultType','Slipper');
 if(!s.invoicePrefix)await setSetting('invoicePrefix','INV');
}
async function load(){
 await migrateBlank();
 const p=await loadPricing(),c=await loadCatalog(),inv=await listInvoices(),meta=await all('meta');
 setState({...p,...c,invoices:inv,erpColumns:meta.find(x=>x.id==='erpColumns')?.value||DEFAULT_ERP_COLUMNS});
}
function syncTabs(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}
function nav(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;syncTabs();render()})}
nav();
async function ensureDraft(){
 if(state.draft&&!state.draft.saved)return state.draft;
 const unsaved=state.invoices.filter(x=>x.saved===false).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0];
 if(unsaved){state.draft=unsaved;return unsaved}
 const d=newDraft(await nextInvoiceNo(state.settings.invoicePrefix||'INV'),state.settings.defaultType||'Slipper');state.draft=d;return d;
}
function recalcDraft(d){d.lines=d.lines.map(l=>calcLine(l,state.settings,state.tiers,state.items));return d}
let autoTimer;
async function autoSave(silent=true){if(!state.draft)return;recalcDraft(state.draft);state.draft.updatedAt=new Date().toISOString();try{await autosaveInvoice(state.draft);state.invoices=await listInvoices();if(!silent)toast('تم الحفظ التلقائي','ok')}catch(e){console.error(e)}}
function scheduleAuto(){clearTimeout(autoTimer);autoTimer=setTimeout(()=>autoSave(true),25)}
function supplierName(id){return state.suppliers.find(x=>x.id===id)?.name||''}
function invoiceTotal(d){return d.lines.reduce((s,l)=>s+num(l.total),0)}
function piecesTotal(d){return d.lines.reduce((s,l)=>s+num(l.pieces),0)}
function statusHTML(l){const m={ok:['مطابق','ok'],manual:['تعديل يدوي','warn'],'multiple-match':['أكثر من صنف','warn'],'manual-no-item':['يدوي بدون صنف ERP','danger'],'no-tier':['لا توجد شريحة','danger'],'no-item':['لا يوجد صنف ERP','danger']};const [t,c]=m[l.status]||['مراجعة','warn'];return `<span class="status ${c}">${t}</span>`}
async function render(){const views={invoice:renderInvoice,saved:renderSaved,catalog:renderCatalog,pricing:renderPricing,export:renderERP,backup:renderBackup};await (views[state.view]||renderInvoice)()}
function itemTypeOptions(v){return [{key:'Slipper',label:'Slipper'},{key:'Winter',label:'Winter'}].map(t=>`<option value="${t.key}" ${v===t.key?'selected':''}>${t.label}</option>`).join('')}

function lineRow(l,i){
 const typeOpts=itemTypeOptions(l.type);
 return `<tr data-line="${esc(l.id)}"><td>${i+1}</td><td><select data-k="type">${typeOpts}</select></td><td><input data-k="unit" type="number" min="1" step="1" inputmode="numeric" value="${num(l.unit)||12}"></td><td><input data-k="qty" type="number" min="0" step="1" inputmode="numeric" value="${num(l.qty)||0}"></td><td><input data-k="purchaseCartonPrice" type="number" min="0" step="0.01" inputmode="decimal" value="${num(l.purchaseCartonPrice??l.cartonPrice)||0}"></td><td><input data-k="discountRate" type="number" min="0" max="100" step="0.01" inputmode="decimal" value="${num(l.discountRate)}"></td><td>${money(l.purchasePerPiece)}</td><td>${money(l.costPerPiece)}</td><td>${money(l.basisPrice)}</td><td>${l.prePrice==null?'—':money(l.prePrice)}</td><td><input data-k="manualFinalPrice" type="number" min="0" step="0.01" inputmode="decimal" placeholder="تلقائي" value="${l.manualFinalPrice??''}"></td><td>${esc(l.erpName||'—')}</td><td>${esc(l.barcode||'—')}</td><td>${num(l.pieces)}</td><td>${money(l.total)}</td><td>${statusHTML(l)}</td><td><input data-k="notes" value="${esc(l.notes||'')}" placeholder="ملاحظة"></td><td><button class="btn danger small" data-del>حذف</button></td></tr>`
}
function mobileLineCard(l,i){
 return `<article class="line-card" data-line-mobile="${esc(l.id)}"><div class="line-card-head"><b>#${i+1} · ${esc(l.erpName||'صنف جديد')}</b><button class="btn danger small" data-del-mobile>حذف</button></div><div class="line-grid"><div class="field"><label>النوع</label><select data-k="type">${itemTypeOptions(l.type)}</select></div><div class="field"><label>الوحدة</label><input data-k="unit" type="number" min="1" value="${num(l.unit)||12}"></div><div class="field"><label>كمية الدستة/الكرتونة</label><input data-k="qty" type="number" min="0" value="${num(l.qty)||0}"></div><div class="field"><label>سعر الشراء للدستة/الكرتونة</label><input data-k="purchaseCartonPrice" type="number" step="0.01" value="${num(l.purchaseCartonPrice??l.cartonPrice)||0}"></div><div class="field"><label>خصم المورد %</label><input data-k="discountRate" type="number" min="0" max="100" step="0.01" value="${num(l.discountRate)}"></div><div class="mini-stat"><span>سعر الشراء/قطعة</span><b>${money(l.purchasePerPiece)}</b></div><div class="mini-stat"><span>التكلفة/قطعة</span><b>${money(l.costPerPiece)}</b></div><div class="mini-stat"><span>أساس التسعير</span><b>${money(l.basisPrice)}</b></div><div class="mini-stat"><span>السعر قبل التقريب</span><b>${l.prePrice==null?'—':money(l.prePrice)}</b></div><div class="field"><label>سعر البيع النهائي</label><input data-k="manualFinalPrice" type="number" step="0.01" placeholder="تلقائي" value="${l.manualFinalPrice??''}"></div></div><div class="line-result"><span>ERP: <b data-mobile-erp>${esc(l.erpName||'—')}</b></span><span>الباركود: <b data-mobile-barcode>${esc(l.barcode||'—')}</b></span><span>الكمية: <b data-mobile-pieces>${num(l.pieces)}</b></span><span>الإجمالي: <b data-mobile-total>${money(l.total)}</b></span><span data-mobile-status>${statusHTML(l)}</span></div><div class="field"><label>ملاحظات</label><input data-k="notes" value="${esc(l.notes||'')}" placeholder="ملاحظة"></div></article>`
}

async function renderInvoice(){
 const d=await ensureDraft();recalcDraft(d);const draftToday=todayISO();
 const supplierOptions=state.suppliers.map(s=>`<option value="${esc(s.id)}" ${s.id===d.supplierId?'selected':''}>${esc(s.name)}${s.code?` — ${esc(s.code)}`:''}</option>`).join('');
 app.innerHTML=`<section class="grid"><div class="card hero-card"><div class="toolbar space"><div><h2>🧾 فاتورة تسعير شراء</h2><div class="muted">سعر الشراء → الخصم → التكلفة → أساس التسعير → الشريحة → سعر المستهلك</div></div><div class="toolbar"><span class="status ${d.saved?'ok':'warn'}">${d.saved?'محفوظ نهائيًا':'مسودة محفوظة تلقائيًا'}</span><button class="btn" id="newInv">فاتورة جديدة</button><button class="btn primary" id="saveInv">حفظ نهائي</button></div></div><div class="invoice-head" style="margin-top:12px"><div class="field"><label>رقم الفاتورة</label><input value="${esc(d.invoiceNo)}" readonly></div><div class="field"><label>التاريخ</label><input type="date" value="${d.saved?esc(d.invoiceDate):draftToday}" readonly></div><div class="field"><label>المورد</label><select id="supplier"><option value="">اختر المورد</option>${supplierOptions}</select></div><div class="field"><label>نوع التسعير الافتراضي</label><select id="type">${itemTypeOptions(d.type)}</select><div class="muted tiny">يُحفظ اختيارك ويظل افتراضيًا حتى تغيّره.</div></div><div class="field"><label>حالة ERP</label><select id="erpEntered"><option value="false" ${!d.erpEntered?'selected':''}>لم تدخل ERP بعد</option><option value="true" ${d.erpEntered?'selected':''}>تم إدخالها في ERP</option></select></div><div class="field"><label>رقم فاتورة ERP</label><input id="erpInvoiceNo" value="${esc(d.erpInvoiceNo||'')}" placeholder="مثال: 25114" ${d.erpEntered?'':'disabled'}></div></div><div class="note" style="margin-top:10px">كل حرف تكتبه في الفاتورة يُحفظ محليًا تلقائيًا. لو قفل التطبيق فجأة، تستعيد آخر مسودة.</div></div>
 <div class="summary"><div class="card"><div class="muted">إجمالي الفاتورة</div><div class="stat">${money(invoiceTotal(d))}</div></div><div class="card"><div class="muted">عدد الأصناف</div><div class="stat">${d.lines.length}</div></div><div class="card"><div class="muted">الكمية بالقطعة</div><div class="stat">${piecesTotal(d)}</div></div><div class="card"><div class="muted">أساس الربح</div><div><span class="pill">${state.settings.marginBasis==='purchase'?'سعر الشراء':'التكلفة الفعلية'}</span></div></div></div>
 <div class="card"><div class="toolbar space"><div><h3>تفاصيل الفاتورة</h3><div class="muted tiny">سعر الشراء والتكلفة منفصلان. مثال: شراء 50 وخصم 5% = تكلفة 47.50.</div></div><button class="btn primary" id="addLine">+ إضافة صنف</button></div><div class="desktop-only table-wrap"><table class="data-table invoice-table"><thead><tr><th>#</th><th>النوع</th><th>الوحدة</th><th>كمية الدستة/الكرتونة</th><th>سعر الشراء/الدستة</th><th>خصم المورد %</th><th>شراء/قطعة</th><th>التكلفة/قطعة</th><th>أساس التسعير</th><th>قبل التقريب</th><th>سعر البيع النهائي</th><th>اسم ERP</th><th>الباركود</th><th>الكمية</th><th>الإجمالي</th><th>الحالة</th><th>ملاحظات</th><th></th></tr></thead><tbody>${d.lines.length?d.lines.map(lineRow).join(''):`<tr><td colspan="18" class="empty">أضف أول صنف للبدء.</td></tr>`}</tbody></table></div><div class="mobile-only line-list">${d.lines.length?d.lines.map(mobileLineCard).join(''):`<div class="empty">أضف أول صنف للبدء.</div>`}</div></div>
 <div class="card"><div class="toolbar space"><div><b>📎 الفاتورة الأصلية</b><div class="muted tiny">ارفع صورة أو PDF، وسيُحفظ محليًا مع الفاتورة.</div></div><div class="toolbar"><button class="btn" id="attach">رفع الفاتورة</button>${d.attachmentId?'<button class="btn" id="openAttachment">فتح المرفق</button>':''}</div></div></div>
 <div class="card"><div class="toolbar"><button class="btn accent" id="image">📷 صورة ومشاركة</button><button class="btn" id="print">🖨️ طباعة حرارية</button><button class="btn" id="erpExport">📤 تصدير ERP</button><button class="btn" id="csvExport">CSV</button></div><div class="muted tiny" style="margin-top:8px">الطباعة 58/80mm مع هوامش أمان. المشاركة تعمل عبر Share في iPhone/Android عند توفرها.</div></div></section>`;
 bindInvoice(d);
 document.getElementById('addLine').onclick=()=>{d.lines.push({id:uid('line'),type:d.type,unit:12,qty:1,purchaseCartonPrice:0,discountRate:0,manualFinalPrice:'',notes:''});scheduleAuto();render()};
 document.getElementById('newInv').onclick=async()=>{if(d.lines.length&&!d.saved&&!confirm('المسودة الحالية محفوظة تلقائيًا. بدء فاتورة جديدة؟'))return;state.draft=newDraft(await nextInvoiceNo(state.settings.invoicePrefix||'INV'),state.settings.defaultType||'Slipper');render()};
 document.getElementById('saveInv').onclick=async()=>{if(!d.supplierId){toast('اختر المورد أولًا','error');return}if(!d.lines.length){toast('أضف صنفًا واحدًا على الأقل','error');return}recalcDraft(d);if(d.erpEntered&&!String(d.erpInvoiceNo||'').trim()){toast('اكتب رقم فاتورة ERP قبل الحفظ','error');return}const bad=d.lines.filter(x=>!['ok','manual'].includes(x.status));if(bad.length&&!confirm(`هناك ${bad.length} سطر يحتاج مراجعة. هل تريد الحفظ رغم ذلك؟`))return;d.supplierName=supplierName(d.supplierId);d.invoiceDate=todayISO();d.saved=true;await saveInvoice(d);state.invoices=await listInvoices();toast('تم حفظ الفاتورة نهائيًا','ok');render()};
 document.getElementById('attach').onclick=()=>document.getElementById('attachmentInput').click();
 document.getElementById('image').onclick=()=>shareImage({...d,supplierName:supplierName(d.supplierId),invoiceDate:d.saved?d.invoiceDate:todayISO()});
 document.getElementById('print').onclick=()=>printInvoice({...d,supplierName:supplierName(d.supplierId),invoiceDate:d.saved?d.invoiceDate:todayISO()});
 document.getElementById('erpExport').onclick=()=>exportERP({...d,supplierName:supplierName(d.supplierId),invoiceDate:d.saved?d.invoiceDate:todayISO()},state.erpColumns);
 document.getElementById('csvExport').onclick=()=>exportCSV({...d,supplierName:supplierName(d.supplierId),invoiceDate:d.saved?d.invoiceDate:todayISO()},state.erpColumns);
 document.getElementById('attachmentInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>12*1024*1024){toast('حجم المرفق أكبر من 12MB','error');return}const id=uid('att');await put('attachments',{id,invoiceId:d.id,name:f.name,type:f.type,size:f.size,blob:f,createdAt:new Date().toISOString()});d.attachmentId=id;d.attachmentName=f.name;d.attachmentType=f.type;await autoSave(true);toast('تم حفظ الفاتورة الأصلية','ok');render()};
 document.getElementById('openAttachment')?.addEventListener('click',()=>openAttachment(d.attachmentId));
}
function bindInvoice(d){
 const set=(key,val)=>{d[key]=val;d.updatedAt=new Date().toISOString();scheduleAuto()};
 document.getElementById('supplier').onchange=e=>set('supplierId',e.target.value);
 document.getElementById('type').onchange=async e=>{d.type=e.target.value;await setSetting('defaultType',d.type);state.settings.defaultType=d.type;scheduleAuto();toast(`تم حفظ النوع الافتراضي: ${d.type}`);render()};
 document.getElementById('erpEntered').onchange=e=>{d.erpEntered=e.target.value==='true';if(!d.erpEntered)d.erpInvoiceNo='';scheduleAuto();render()};
 document.getElementById('erpInvoiceNo').oninput=e=>set('erpInvoiceNo',e.target.value);
 const bindLine=(tr,id)=>{const l=d.lines.find(x=>x.id===id);tr.querySelectorAll('[data-k]').forEach(inp=>inp.addEventListener('input',e=>{const k=e.target.dataset.k;l[k]=e.target.value;Object.assign(l,calcLine(l,state.settings,state.tiers,state.items));updateLineUI(tr,l);scheduleAuto()}));tr.querySelector('[data-del]')?.addEventListener('click',()=>{d.lines=d.lines.filter(x=>x.id!==id);scheduleAuto();render()})};
 document.querySelectorAll('tr[data-line]').forEach(tr=>bindLine(tr,tr.dataset.line));
 document.querySelectorAll('[data-line-mobile]').forEach(card=>{const id=card.dataset.lineMobile,l=d.lines.find(x=>x.id===id);card.querySelectorAll('[data-k]').forEach(inp=>inp.addEventListener('input',e=>{l[e.target.dataset.k]=e.target.value;Object.assign(l,calcLine(l,state.settings,state.tiers,state.items));updateMobileLineUI(card,l);scheduleAuto()}));card.querySelector('[data-del-mobile]')?.addEventListener('click',()=>{d.lines=d.lines.filter(x=>x.id!==id);scheduleAuto();render()})});
}
function updateLineUI(tr,l){const cells=tr.cells;if(cells[6])cells[6].textContent=money(l.purchasePerPiece);if(cells[7])cells[7].textContent=money(l.costPerPiece);if(cells[8])cells[8].textContent=money(l.basisPrice);if(cells[9])cells[9].textContent=l.prePrice==null?'—':money(l.prePrice);if(cells[11])cells[11].textContent=l.erpName||'—';if(cells[12])cells[12].textContent=l.barcode||'—';if(cells[13])cells[13].textContent=num(l.pieces);if(cells[14])cells[14].textContent=money(l.total);if(cells[15])cells[15].innerHTML=statusHTML(l)}
function updateMobileLineUI(card,l){card.querySelector('[data-mobile-erp]').textContent=l.erpName||'—';card.querySelector('[data-mobile-barcode]').textContent=l.barcode||'—';card.querySelector('[data-mobile-pieces]').textContent=num(l.pieces);card.querySelector('[data-mobile-total]').textContent=money(l.total);card.querySelector('[data-mobile-status]').innerHTML=statusHTML(l);card.querySelectorAll('.mini-stat b')[0].textContent=money(l.purchasePerPiece);card.querySelectorAll('.mini-stat b')[1].textContent=money(l.costPerPiece);card.querySelectorAll('.mini-stat b')[2].textContent=money(l.basisPrice);card.querySelectorAll('.mini-stat b')[3].textContent=l.prePrice==null?'—':money(l.prePrice);card.querySelector('.line-card-head b').textContent=`#${[...document.querySelectorAll('[data-line-mobile]')].indexOf(card)+1} · ${l.erpName||'صنف جديد'}`}

async function renderSaved(){
 const invs=await listInvoices();state.invoices=invs;const q=String(state.filters.saved||'').trim().toLowerCase();const rows=invs.filter(i=>!q||[i.invoiceNo,i.invoiceDate,i.supplierName,i.type,i.erpInvoiceNo].join(' ').toLowerCase().includes(q));
 app.innerHTML=`<section class="grid"><div class="card"><div class="toolbar space"><div><h2>📚 الفواتير المحفوظة</h2><div class="muted">المسودات، الفواتير النهائية، وحالة ERP.</div></div><button class="btn primary" id="newSaved">+ فاتورة جديدة</button></div><div class="toolbar" style="margin-top:10px"><input id="savedSearch" class="search" placeholder="بحث برقم الفاتورة أو المورد أو ERP" value="${esc(state.filters.saved)}"></div><div class="desktop-only table-wrap" style="margin-top:12px"><table class="data-table"><thead><tr><th>رقم الفاتورة</th><th>التاريخ</th><th>المورد</th><th>النوع</th><th>الإجمالي</th><th>ERP</th><th>المرفق</th><th>آخر تعديل</th><th>إجراءات</th></tr></thead><tbody>${rows.map(i=>`<tr><td>${esc(i.invoiceNo)}</td><td>${esc(i.invoiceDate)}</td><td>${esc(i.supplierName||supplierName(i.supplierId))}</td><td>${esc(i.type)}</td><td>${money(invoiceTotal(i))}</td><td>${i.erpEntered?`تم · ${esc(i.erpInvoiceNo||'—')}`:'لم تدخل'}</td><td>${i.attachmentId?'نعم':'لا'}</td><td>${esc(i.updatedAt||'')}</td><td class="row-actions"><button class="btn small" data-open="${i.id}">فتح</button><button class="btn small" data-image="${i.id}">صورة</button><button class="btn small" data-export="${i.id}">ERP</button><button class="btn danger small" data-delete="${i.id}">حذف</button></td></tr>`).join('')||'<tr><td colspan="9" class="empty">لا توجد فواتير محفوظة.</td></tr>'}</tbody></table></div><div class="mobile-only card-list">${rows.map(i=>`<article class="record-card"><div><b>${esc(i.invoiceNo)}</b><span class="pill">${esc(i.type)}</span></div><div>${esc(i.supplierName||supplierName(i.supplierId))}</div><div class="muted">${esc(i.invoiceDate)} · ${money(invoiceTotal(i))}</div><div>${i.erpEntered?`ERP: ${esc(i.erpInvoiceNo||'—')}`:'ERP: لم تدخل'}</div><div class="toolbar"><button class="btn small" data-open="${i.id}">فتح</button><button class="btn small" data-image="${i.id}">صورة</button><button class="btn small" data-export="${i.id}">ERP</button><button class="btn danger small" data-delete="${i.id}">حذف</button></div></article>`).join('')||'<div class="empty">لا توجد فواتير محفوظة.</div>'}</div></div></section>`;
 document.getElementById('newSaved').onclick=async()=>{state.draft=newDraft(await nextInvoiceNo(state.settings.invoicePrefix||'INV'),state.settings.defaultType||'Slipper');state.view='invoice';syncTabs();render()};document.getElementById('savedSearch').oninput=e=>{state.filters.saved=e.target.value;renderSaved()};
 document.querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{state.draft=await getInvoice(b.dataset.open);state.view='invoice';syncTabs();render()});
 document.querySelectorAll('[data-image]').forEach(b=>{b.onclick=()=>{const i=invs.find(x=>x.id===b.dataset.image);if(i)shareImage({...i,supplierName:i.supplierName||supplierName(i.supplierId)})}});
 document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{const i=invs.find(x=>x.id===b.dataset.export);if(i)exportERP({...i,supplierName:i.supplierName||supplierName(i.supplierId)},state.erpColumns)});
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف الفاتورة؟'))return;await deleteInvoice(b.dataset.delete);if(state.draft?.id===b.dataset.delete)state.draft=null;state.invoices=await listInvoices();render()});
}

async function renderCatalog(){
 const iq=String(state.filters.items||'').toLowerCase();const items=state.items.filter(x=>!iq||[x.name,x.itemId,x.barcode,x.sellPriceBeforeDiscount,x.salePriceAfterDiscount,x.supplier,x.mainCategory,x.subCategory,x.lrp,x.lrb].join(' ').toLowerCase().includes(iq));
 app.innerHTML=`<section class="grid"><div class="card hero-card"><div class="toolbar space"><div><h2>📦 البيانات الأساسية</h2><div class="muted">النظام يبدأ بدون موردين أو أصناف. استورد ملف ERP وحدد بنفسك الورقة وصف العناوين وربط الحقول.</div></div><div class="toolbar"><button class="btn primary" id="importMaster">📥 استيراد بيانات ERP</button><button class="btn" id="templateBtn">⬇ نموذج CSV</button></div></div><div class="note" style="margin-top:10px">لا توجد بيانات تجريبية. كل الموردين والأصناف والأكواد والأسعار تأتي من ملفك أنت.</div></div>
 <div class="card"><div class="toolbar space"><h3>بحث في الأصناف</h3><span class="pill">${state.items.length} صنف</span></div><input id="itemSearch" class="search" placeholder="اسم الصنف / ID / باركود / مورد / قسم / LRP / LRB" value="${esc(state.filters.items)}"><div class="desktop-only table-wrap" style="margin-top:10px"><table class="data-table"><thead><tr><th>النوع</th><th>اسم الصنف</th><th>ID</th><th>Barcode</th><th>المورد</th><th>القسم الرئيسي</th><th>القسم الفرعي</th><th>السعر</th><th>سعر البيع/قبل الخصم</th><th>السعر بعد الخصم</th><th>سعر الشراء</th><th>التكلفة</th><th>LRP</th><th>LRB</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.name)}</td><td>${esc(x.itemId)}</td><td>${esc(x.barcode)}</td><td>${esc(x.supplier)}</td><td>${esc(x.mainCategory)}</td><td>${esc(x.subCategory)}</td><td>${money(x.basePrice)}</td><td>${money(x.salePriceBeforeDiscount)}</td><td>${money(x.salePriceAfterDiscount)}</td><td>${money(x.purchasePrice)}</td><td>${money(x.cost)}</td><td>${esc(x.lrp)}</td><td>${esc(x.lrb)}</td><td><button class="btn danger small" data-ri="${x.id}">حذف</button></td></tr>`).join('')||'<tr><td colspan="15" class="empty">لا توجد بيانات.</td></tr>'}</tbody></table></div><div class="mobile-only card-list">${items.map(x=>`<article class="record-card"><div class="record-title"><b>${esc(x.name||'بدون اسم')}</b><span class="pill">${esc(x.type)}</span></div><div class="record-grid"><span><b>ID:</b> ${esc(x.itemId)}</span><span><b>Barcode:</b> ${esc(x.barcode)}</span><span><b>المورد:</b> ${esc(x.supplier)}</span><span><b>القسم:</b> ${esc(x.mainCategory)} / ${esc(x.subCategory)}</span><span><b>السعر:</b> ${money(x.basePrice)}</span><span><b>البيع/قبل الخصم:</b> ${money(x.salePriceBeforeDiscount)}</span><span><b>بعد الخصم:</b> ${money(x.salePriceAfterDiscount)}</span><span><b>الشراء:</b> ${money(x.purchasePrice)}</span><span><b>التكلفة:</b> ${money(x.cost)}</span><span><b>LRP:</b> ${esc(x.lrp)}</span><span><b>LRB:</b> ${esc(x.lrb)}</span></div><button class="btn danger small" data-ri="${x.id}">حذف</button></article>`).join('')||'<div class="empty">لا توجد بيانات.</div>'}</div></div>
 <div class="card"><h3>👥 الموردون المستخرجون من البيانات</h3><div class="muted tiny">الموردون هنا يُنشأون تلقائيًا من ملف الأصناف بعد الاستيراد، بدون إدخال بيانات مسبقة.</div><div class="supplier-cards">${state.suppliers.map(s=>`<span class="pill">${esc(s.name)}${s.code?` · ${esc(s.code)}`:''}</span>`).join('')||'<span class="muted">لا يوجد موردون بعد.</span>'}</div></div></section>`;
 document.getElementById('importMaster').onclick=()=>openImportWizard();
 document.getElementById('templateBtn').onclick=downloadTemplate;
 document.getElementById('itemSearch').oninput=e=>{state.filters.items=e.target.value;renderCatalog()};
 document.querySelectorAll('[data-ri]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف الصنف؟'))return;await removeItem(b.dataset.ri);state.items=await all('items');render()});
}
function downloadTemplate(){const headers=IMPORT_FIELDS.map(x=>x[1]);const sample=['مثال صنف','1001','123456789','مثال مورد','SUP-01','أحذية','سليبرات','100','150','135','100','95','LRP-001','LRB-001'];const csv='\uFEFF'+headers.join(',')+'\n'+sample.join(',');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ERP_Master_Import_Template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

let importSession=null;
async function ensureXLSX(){if(window.XLSX)return window.XLSX;await new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';sc.onload=resolve;sc.onerror=()=>reject(new Error('تعذر تحميل محرك Excel. استخدم CSV أو اتصل بالإنترنت ثم حاول مرة أخرى.'));document.head.appendChild(sc)});return window.XLSX}
async function readWorkbook(file){
 if(/\.csv$/i.test(file.name)){const text=await file.text();const rows=parseCSV(text);const headers=Object.keys(rows[0]||{});return {sheets:[{name:'CSV',matrix:[headers,...rows.map(r=>headers.map(h=>r[h]??''))]}]}}
 const XLSX=await ensureXLSX();
 const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});
 return {sheets:wb.SheetNames.map(name=>({name,matrix:XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:'',raw:false})}))};
}
function guessMapping(headers){const norm=headers.map(normalizeKey);const find=(patterns)=>{const i=norm.findIndex(h=>patterns.some(p=>h.includes(normalizeKey(p))));return i>=0?String(i):''};return {name:find(['اسم الصنف','الصنف','itemname','name']),itemId:find(['id','itemid','كود الصنف']),barcode:find(['barcode','باركود','الباركود']),supplier:find(['المورد','supplier']),supplierCode:find(['كود المورد','suppliercode']),mainCategory:find(['القسم الرئيسي','maincategory']),subCategory:find(['القسم الفرعي','القسم','subcategory']),basePrice:find(['السعر','price']),salePriceBeforeDiscount:find(['سعر البيع','قبل الخصم','saleprice']),salePriceAfterDiscount:find(['السعر بعد الخصم','بعد الخصم','discountedprice']),purchasePrice:find(['سعر الشراء','purchase']),cost:find(['التكلفة','cost']),lrp:find(['lrp']),lrb:find(['lrb'])}}
function mappingOptions(headers,selected){return `<option value="">— غير مربوط —</option>`+headers.map((h,i)=>`<option value="${i}" ${String(selected)===String(i)?'selected':''}>${esc(h||`عمود ${i+1}`)}</option>`).join('')}
function openImportWizard(){
 const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.id='importModal';overlay.innerHTML=`<div class="modal"><div class="toolbar space"><div><h2>📥 استيراد البيانات الأساسية</h2><div class="muted tiny">اختر الملف → الورقة → صف العناوين → اربط الحقول → راجع المعاينة → استيراد.</div></div><button class="btn" id="closeImport">إغلاق</button></div><div class="import-steps"><span>1 الملف</span><span>2 الورقة</span><span>3 العناوين</span><span>4 الربط</span><span>5 المعاينة</span></div><div id="importBody"></div></div>`;document.body.appendChild(overlay);document.getElementById('closeImport').onclick=()=>overlay.remove();renderImportStep1();}
function renderImportStep1(){const body=document.getElementById('importBody');body.innerHTML=`<div class="drop big-drop"><input id="masterFile" type="file" accept=".xlsx,.xls,.csv"><h3>اختر ملف البيانات الأساسية</h3><p class="muted">يمكن أن يحتوي الملف على أعمدة كثيرة؛ أنت ستحدد بنفسك أي عمود يمثل كل حقل.</p></div>`;document.getElementById('masterFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{importSession={file:f,workbook:await readWorkbook(f)};renderImportStep2()}catch(err){console.error(err);toast(err.message||'تعذر قراءة الملف','error')}}}
function renderImportStep2(){const body=document.getElementById('importBody');body.innerHTML=`<div class="grid grid-2"><div class="field"><label>ورقة العمل</label><select id="sheetSelect">${importSession.workbook.sheets.map((s,i)=>`<option value="${i}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>نوع الأصناف المستوردة</label><select id="importType">${itemTypeOptions(state.settings.defaultType||'Slipper')}</select></div></div><div id="sheetPreview" class="preview-grid" style="margin-top:12px"></div><button class="btn primary" id="toHeaders" style="margin-top:12px">التالي: اختيار صف العناوين</button>`;const update=()=>{const s=importSession.workbook.sheets[Number(document.getElementById('sheetSelect').value)];importSession.sheetIndex=Number(document.getElementById('sheetSelect').value);importSession.type=document.getElementById('importType').value;document.getElementById('sheetPreview').innerHTML=renderMatrixPreview(s.matrix,0,8,8)};document.getElementById('sheetSelect').onchange=update;document.getElementById('importType').onchange=e=>importSession.type=e.target.value;document.getElementById('toHeaders').onclick=()=>renderImportStep3();update()}
function renderImportStep3(){const s=importSession.workbook.sheets[importSession.sheetIndex];const max=Math.min(s.matrix.length,30);document.getElementById('importBody').innerHTML=`<div class="note">حدد الصف الذي يحتوي على أسماء الأعمدة. لا يشترط أن يكون الصف الأول.</div><div class="header-row-list">${Array.from({length:max},(_,i)=>`<label class="header-row-choice"><input type="radio" name="headerRow" value="${i}" ${i===0?'checked':''}> الصف ${i+1}<span>${esc((s.matrix[i]||[]).slice(0,8).join(' | '))}</span></label>`).join('')}</div><button class="btn primary" id="toMapping">التالي: ربط الحقول</button>`;document.getElementById('toMapping').onclick=()=>{importSession.headerRow=Number(document.querySelector('input[name="headerRow"]:checked').value);renderImportStep4()}}
function renderImportStep4(){const s=importSession.workbook.sheets[importSession.sheetIndex];const headers=(s.matrix[importSession.headerRow]||[]).map(v=>String(v??''));importSession.headers=headers;importSession.mapping={...guessMapping(headers),...(importSession.mapping||{})};document.getElementById('importBody').innerHTML=`<div class="mapping-grid">${IMPORT_FIELDS.map(([key,label])=>`<div class="mapping-row"><b>${label}</b><select data-map="${key}">${mappingOptions(headers,importSession.mapping[key])}</select></div>`).join('')}</div><div class="grid grid-2" style="margin-top:12px"><div class="field"><label>نوع التسعير للأصناف</label><select id="mapType">${itemTypeOptions(importSession.type||state.settings.defaultType||'Slipper')}</select></div><div class="field"><label>هل أستبدل بيانات الأصناف الموجودة بنفس ID؟</label><select id="upsertMode"><option value="update">تحديث الموجود وإضافة الجديد</option><option value="append">إضافة فقط</option></select></div></div><button class="btn primary" id="toPreview" style="margin-top:12px">التالي: معاينة البيانات</button>`;document.querySelectorAll('[data-map]').forEach(s=>s.onchange=e=>importSession.mapping[e.target.dataset.map]=e.target.value);document.getElementById('mapType').onchange=e=>importSession.type=e.target.value;document.getElementById('toPreview').onclick=()=>{importSession.upsert=document.getElementById('upsertMode').value;renderImportStep5()}}
function renderImportStep5(){const s=importSession.workbook.sheets[importSession.sheetIndex],m=importSession.mapping,rows=s.matrix.slice(importSession.headerRow+1).filter(r=>r.some(v=>String(v??'').trim()));importSession.rows=rows;const sample=rows.slice(0,10);const val=(r,k)=>{const i=m[k];return i===''||i==null?'':r[Number(i)]??''};document.getElementById('importBody').innerHTML=`<div class="summary"><div class="card"><div class="muted">عدد الصفوف</div><div class="stat">${rows.length}</div></div><div class="card"><div class="muted">عدد الأعمدة</div><div class="stat">${s.matrix[importSession.headerRow]?.length||0}</div></div><div class="card"><div class="muted">النوع</div><div class="stat" style="font-size:18px">${esc(importSession.type)}</div></div><div class="card"><div class="muted">المصدر</div><div class="stat" style="font-size:15px">${esc(importSession.workbook.sheets[importSession.sheetIndex].name)}</div></div></div><div class="table-wrap" style="margin-top:12px"><table class="data-table"><thead><tr><th>اسم الصنف</th><th>ID</th><th>Barcode</th><th>المورد</th><th>القسم الرئيسي</th><th>القسم الفرعي</th><th>السعر</th><th>البيع/قبل الخصم</th><th>بعد الخصم</th><th>الشراء</th><th>التكلفة</th><th>LRP</th><th>LRB</th></tr></thead><tbody>${sample.map(r=>`<tr><td>${esc(val(r,'name'))}</td><td>${esc(val(r,'itemId'))}</td><td>${esc(val(r,'barcode'))}</td><td>${esc(val(r,'supplier'))}</td><td>${esc(val(r,'mainCategory'))}</td><td>${esc(val(r,'subCategory'))}</td><td>${esc(val(r,'basePrice'))}</td><td>${esc(val(r,'salePriceBeforeDiscount'))}</td><td>${esc(val(r,'salePriceAfterDiscount'))}</td><td>${esc(val(r,'purchasePrice'))}</td><td>${esc(val(r,'cost'))}</td><td>${esc(val(r,'lrp'))}</td><td>${esc(val(r,'lrb'))}</td></tr>`).join('')}</tbody></table></div><div class="note" style="margin-top:12px">سيتم إنشاء الموردين تلقائيًا من عمود المورد، مع منع التكرار. سعر البيع = السعر قبل الخصم كحقل واحد، والسعر بعد الخصم حقل مستقل.</div><div class="toolbar" style="margin-top:12px"><button class="btn" id="backMap">رجوع</button><button class="btn primary" id="confirmImport">✅ تأكيد الاستيراد</button></div>`;document.getElementById('backMap').onclick=renderImportStep4;document.getElementById('confirmImport').onclick=commitImport}
async function commitImport(){const s=importSession.workbook.sheets[importSession.sheetIndex],m=importSession.mapping,rows=importSession.rows;const val=(r,k)=>{const i=m[k];return i===''||i==null?'':String(r[Number(i)]??'').trim()};let added=0,updated=0;const existing=await all('items');const byId=new Map(existing.filter(x=>x.itemId).map(x=>[String(x.itemId),x]));const suppliersByKey=new Map((await all('suppliers')).map(x=>[`${x.name}|${x.code||''}`,x]));const newItems=[];const newSuppliers=[];for(const r of rows){const name=val(r,'name');if(!name)continue;const itemId=val(r,'itemId'),supplier=val(r,'supplier'),supplierCode=val(r,'supplierCode');if(supplier){const key=`${supplier}|${supplierCode}`;if(!suppliersByKey.has(key)){const sp={id:uid('sup'),name:supplier,code:supplierCode};suppliersByKey.set(key,sp);newSuppliers.push(sp)}}const item={id:uid('item'),type:importSession.type||'Slipper',name,itemId,barcode:val(r,'barcode'),supplier,supplierCode,mainCategory:val(r,'mainCategory'),subCategory:val(r,'subCategory'),basePrice:num(val(r,'basePrice')),salePriceBeforeDiscount:num(val(r,'salePriceBeforeDiscount')),salePriceAfterDiscount:num(val(r,'salePriceAfterDiscount')),sellPrice:num(val(r,'salePriceAfterDiscount')),purchasePrice:num(val(r,'purchasePrice')),cost:num(val(r,'cost')),lrp:val(r,'lrp'),lrb:val(r,'lrb')};const old=itemId&&byId.get(itemId);if(old&&importSession.upsert==='update'){item.id=old.id;updated++}else added++;newItems.push(item)}if(newSuppliers.length)await putMany('suppliers',newSuppliers);if(newItems.length)await putMany('items',newItems);state.suppliers=await all('suppliers');state.items=await all('items');document.getElementById('importModal')?.remove();toast(`تم الاستيراد: ${added} جديد · ${updated} تحديث`,'ok');render()}
function renderMatrixPreview(matrix,start,count,cols){return `<div class="table-wrap"><table class="data-table"><tbody>${matrix.slice(start,start+count).map((r,i)=>`<tr><th>صف ${start+i+1}</th>${r.slice(0,cols).map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}

async function renderPricing(){
 const tiers=[...state.tiers].sort((a,b)=>a.type.localeCompare(b.type)||num(a.from)-num(b.from));
 app.innerHTML=`<section class="grid grid-2"><div class="card"><h2>⚙️ إعدادات التسعير</h2><div class="field"><label>نسبة الربح</label><input id="margin" type="number" min="0" step="0.01" value="${num(state.settings.marginRate)*100}"><div class="muted tiny">مثال 35 = 35%.</div></div><div class="field" style="margin-top:10px"><label>أساس حساب نسبة الربح</label><select id="marginBasis"><option value="cost" ${state.settings.marginBasis!=='purchase'?'selected':''}>التكلفة الفعلية</option><option value="purchase" ${state.settings.marginBasis==='purchase'?'selected':''}>سعر الشراء</option></select><div class="muted tiny">مثال: شراء 50 وخصم 5% ⇒ التكلفة 47.50. اختر على أيهما تحسب النسبة.</div></div><div class="field" style="margin-top:10px"><label>نوع التسعير الافتراضي</label><select id="defaultType">${itemTypeOptions(state.settings.defaultType||'Slipper')}</select></div><div class="field" style="margin-top:10px"><label>بادئة أرقام الفواتير</label><input id="prefix" value="${esc(state.settings.invoicePrefix||'INV')}"></div><button class="btn primary" id="saveSettings" style="margin-top:10px">حفظ الإعدادات</button><div class="note" style="margin-top:10px">سعر الشراء والتكلفة وسعر البيع قبل الخصم والسعر بعد الخصم حقول منفصلة. البحث عن صنف ERP يعتمد على السعر بعد الخصم.</div></div><div class="card"><div class="toolbar space"><h2>شرائح الأسعار</h2><button class="btn primary" id="addTier">+ شريحة</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>النوع</th><th>من</th><th>إلى</th><th>سعر البيع بعد الخصم</th><th>مفعلة</th><th>الحالة</th><th></th></tr></thead><tbody>${tiers.map(t=>`<tr><td><select data-t="type" data-id="${t.id}">${itemTypeOptions(t.type)}</select></td><td><input data-t="from" data-id="${t.id}" type="number" step="0.01" value="${t.from}"></td><td><input data-t="to" data-id="${t.id}" type="number" step="0.01" value="${t.to}"></td><td><input data-t="price" data-id="${t.id}" type="number" step="0.01" value="${t.price}"></td><td><input data-t="enabled" data-id="${t.id}" type="checkbox" ${t.enabled!==false?'checked':''}></td><td>${tierState(t)}</td><td><button class="btn danger small" data-dt="${t.id}">حذف</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">لا توجد شرائح أسعار بعد. أضف شرائحك الفعلية.</td></tr>'}</tbody></table></div><div class="note" style="margin-top:10px">لن يتم زرع أي أسعار افتراضية من ملف Excel القديم. أنت من يضيف شرائح Slipper وWinter.</div></div></section>`;
 document.getElementById('saveSettings').onclick=async()=>{await setSetting('marginRate',num(document.getElementById('margin').value)/100);await setSetting('marginBasis',document.getElementById('marginBasis').value);await setSetting('defaultType',document.getElementById('defaultType').value);await setSetting('invoicePrefix',document.getElementById('prefix').value.trim()||'INV');state.settings=await getSettings();toast('تم حفظ الإعدادات','ok');render()};
 document.getElementById('addTier').onclick=async()=>{await saveTier({type:state.settings.defaultType||'Slipper',from:0,to:0,price:0,enabled:true});state.tiers=(await loadPricing()).tiers;render()};
 document.querySelectorAll('[data-dt]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف شريحة الأسعار؟'))return;await removeTier(b.dataset.dt);state.tiers=(await loadPricing()).tiers;render()});
 document.querySelectorAll('[data-t]').forEach(inp=>inp.onchange=async()=>{const t=state.tiers.find(x=>x.id===inp.dataset.id);if(inp.dataset.t==='enabled')t.enabled=inp.checked;else if(inp.dataset.t==='type')t.type=inp.value;else t[inp.dataset.t]=num(inp.value);await saveTier(t);state.tiers=(await loadPricing()).tiers;render()});
}
function tierState(t){if(num(t.from)>num(t.to))return'<span class="status danger">الحدود خطأ</span>';const same=state.tiers.filter(x=>x.id!==t.id&&x.type===t.type&&x.enabled!==false);const overlap=same.some(x=>Math.max(num(t.from),num(x.from))<=Math.min(num(t.to),num(x.to)));return overlap?'<span class="status warn">تداخل</span>':'<span class="status ok">سليم</span>'}

function erpKeys(){return [{key:'seq',label:'مسلسل'},{key:'invoiceNo',label:'رقم الفاتورة'},{key:'date',label:'التاريخ'},{key:'supplier',label:'المورد'},{key:'supplierId',label:'كود المورد'},{key:'type',label:'النوع'},{key:'itemName',label:'اسم الصنف ERP'},{key:'itemId',label:'ID'},{key:'barcode',label:'الباركود'},{key:'lrp',label:'LRP'},{key:'lrb',label:'LRB'},{key:'qty',label:'الكمية'},{key:'unit',label:'الوحدة'},{key:'cartonQty',label:'كمية الدستة/الكرتونة'},{key:'purchasePrice',label:'سعر الشراء/قطعة'},{key:'cost',label:'التكلفة/قطعة'},{key:'purchaseCartonPrice',label:'سعر الشراء/الدستة أو الكرتونة'},{key:'sellPrice',label:'السعر بعد الخصم'},{key:'saleBeforeDiscount',label:'سعر البيع / قبل الخصم'},{key:'total',label:'الإجمالي'},{key:'profit',label:'الربح'},{key:'margin',label:'نسبة الربح'},{key:'notes',label:'ملاحظات'}]}
async function renderERP(){
 app.innerHTML=`<section class="grid grid-2"><div class="card"><h2>📤 ترتيب أعمدة ERP</h2><div class="note">ده ترتيب التصدير فقط. قاعدة البيانات الداخلية لها ترتيبها الخاص، أما ملف Excel النهائي فيخرج بنفس تسلسل شاشة ERP الذي ستحدده هنا.</div><div id="erpCols" class="grid" style="margin-top:10px">${state.erpColumns.map((c,i)=>`<div class="erp-row" data-erprow="${i}"><span class="drag-num">${i+1}</span><input data-ek="label" value="${esc(c.label)}"><select data-ek="key">${erpKeys().map(k=>`<option value="${k.key}" ${k.key===c.key?'selected':''}>${k.label}</option>`).join('')}</select><button class="btn danger small" data-delcol="${i}">حذف</button></div>`).join('')}</div><div class="toolbar" style="margin-top:10px"><button class="btn" id="addCol">+ عمود</button><button class="btn" id="resetCols">القالب الافتراضي</button><button class="btn primary" id="saveCols">حفظ الترتيب</button></div></div><div class="card"><h2>معنى الحقول المالية</h2><div class="info-list"><div><b>سعر الشراء:</b> السعر الذي تشتري به قبل الخصم.</div><div><b>التكلفة:</b> التكلفة الفعلية بعد خصم المورد والتسويات.</div><div><b>سعر البيع / قبل الخصم:</b> نفس القيمة عندك، وليسا حقلين مختلفين.</div><div><b>السعر بعد الخصم:</b> السعر الذي يدفعه المستهلك، وهو مفتاح البحث عن صنف ERP.</div></div></div></section>`;
 document.getElementById('addCol').onclick=()=>{state.erpColumns.push({key:'notes',label:'ملاحظات'});render()};document.getElementById('resetCols').onclick=()=>{state.erpColumns=DEFAULT_ERP_COLUMNS.map(x=>({...x}));render()};document.querySelectorAll('[data-delcol]').forEach(b=>b.onclick=()=>{state.erpColumns.splice(Number(b.dataset.delcol),1);render()});document.getElementById('saveCols').onclick=async()=>{state.erpColumns=[...document.querySelectorAll('[data-erprow]')].map(row=>({key:row.querySelector('[data-ek="key"]').value,label:row.querySelector('[data-ek="label"]').value.trim()||'حقل'}));await put('meta',{id:'erpColumns',value:state.erpColumns});toast('تم حفظ ترتيب ERP','ok')};
}
async function renderBackup(){app.innerHTML=`<section class="grid grid-2"><div class="card"><h2>💾 النسخ الاحتياطي والاستعادة</h2><p>كل بيانات النظام محلية. استخدم النسخ الاحتياطي قبل أي تحديث أو تغيير كبير.</p><div class="toolbar"><button class="btn primary" id="backupOut">تصدير نسخة احتياطية</button><button class="btn" id="backupIn">استعادة نسخة</button></div><div class="note" style="margin-top:12px">النسخة تشمل الموردين، الأصناف، الشرائح، الإعدادات، الفواتير والمرفقات.</div><input id="backupFile" type="file" accept="application/json,.json" hidden></div><div class="card"><h2>ℹ️ معلومات النسخة</h2><div class="info-list"><div><b>الإصدار:</b> v${APP_VERSION}</div><div><b>المنشئ:</b> ${esc(CREATOR)}</div><div><b>Build:</b> ${BUILD_DATE}</div><div><b>التخزين:</b> IndexedDB Local-First</div><div><b>المعمارية:</b> Modular PWA</div></div></div></section>`;document.getElementById('backupOut').onclick=()=>exportBackup();document.getElementById('backupIn').onclick=()=>document.getElementById('backupFile').click();document.getElementById('backupFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(!confirm('الاستعادة ستستبدل البيانات المحلية الحالية. هل تريد المتابعة؟'))return;try{await importBackup(f);state.draft=null;await load();toast('تمت الاستعادة','ok');render()}catch(err){console.error(err);toast('ملف النسخة الاحتياطية غير صالح','error')}}}
async function openAttachment(id){const a=await get('attachments',id);if(!a?.blob){toast('المرفق غير موجود','error');return}const url=URL.createObjectURL(a.blob);const w=window.open(url,'_blank');if(!w)toast('اسمح بفتح نافذة جديدة لعرض المرفق','error');setTimeout(()=>URL.revokeObjectURL(url),60000)}
addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();document.getElementById('saveInv')?.click()}});
addEventListener('beforeunload',()=>{if(state.draft){try{recalcDraft(state.draft);autosaveInvoice(state.draft)}catch{}}});
const bootStarted=Date.now();
let dbReady=false;
let bootError=null;
let bootPromise=null;
function renderDbStatus(){
  const el=document.getElementById('dbStatus');
  if(!el)return;
  if(dbReady){el.textContent='● التخزين المحلي جاهز';el.className='db-status ok'}
  else if(bootError){el.textContent='● وضع مؤقت — قاعدة البيانات لم تجهز';el.className='db-status warn'}
  else{el.textContent='● جاري تجهيز التخزين المحلي';el.className='db-status loading'}
}
function renderSafeFallback(){
  app.innerHTML=`<section class="grid"><div class="card hero-card"><div class="toolbar space"><div><h2>نظام تسعير السليبر</h2><div class="muted">النظام يعمل الآن، ويمكنك فتح الشاشات. يتم تجهيز التخزين المحلي في الخلفية.</div></div><span id="dbStatus" class="db-status loading">● جاري تجهيز التخزين المحلي</span></div><div class="note" style="margin-top:12px">لن يتم فقد أي بيانات. إذا تعذر تشغيل IndexedDB سيظهر لك السبب بدل توقف الشاشة.</div><div id="dbError" class="note" style="display:none;margin-top:10px"></div></div><div class="card"><h3>ابدأ من هنا</h3><div class="grid grid-2"><button class="btn primary" id="safeInvoice">🧾 فتح الفاتورة</button><button class="btn" id="safeCatalog">📦 البيانات الأساسية</button><button class="btn" id="safePricing">⚙️ التسعير</button><button class="btn" id="safeERP">📤 ERP</button></div></div></section>`;
  renderDbStatus();
  document.getElementById('safeInvoice').onclick=()=>{state.view='invoice';if(dbReady)render();else renderInvoiceSafe()};
  document.getElementById('safeCatalog').onclick=()=>{state.view='catalog';renderSafeView('catalog')};
  document.getElementById('safePricing').onclick=()=>{state.view='pricing';renderSafeView('pricing')};
  document.getElementById('safeERP').onclick=()=>{state.view='export';renderSafeView('export')};
  if(bootError){const e=document.getElementById('dbError');e.style.display='block';e.innerHTML=`<b>مشكلة التخزين:</b> ${esc(bootError.message||String(bootError))}<div class="toolbar" style="margin-top:8px"><button class="btn danger" id="resetV14">تهيئة التخزين المحلي من جديد</button><button class="btn" id="retryV14">إعادة المحاولة</button></div>`;document.getElementById('resetV14').onclick=resetLocalDb;document.getElementById('retryV14').onclick=()=>location.reload()}
}
function renderInvoiceSafe(){
  const d=state.draft||newDraft('INV-'+todayISO().replaceAll('-','')+'-0001',state.settings.defaultType||'Slipper');
  state.draft=d;
  app.innerHTML=`<section class="grid"><div class="card hero-card"><div class="toolbar space"><div><h2>🧾 فاتورة تسعير شراء</h2><div class="muted">وضع تشغيل مؤقت: التخزين المحلي لم يجهز بعد.</div></div><span id="dbStatus" class="db-status warn">● وضع مؤقت</span></div><div class="invoice-head" style="margin-top:12px"><div class="field"><label>رقم الفاتورة</label><input value="${esc(d.invoiceNo)}" readonly></div><div class="field"><label>التاريخ</label><input value="${todayISO()}" readonly></div><div class="field"><label>المورد</label><input placeholder="سيتم تفعيل الموردين بعد تجهيز التخزين المحلي"></div><div class="field"><label>النوع</label><select>${itemTypeOptions(d.type)}</select></div></div><div class="note" style="margin-top:10px">تم فتح الشاشة بدل تجميد النظام. عند جاهزية التخزين سيعود النظام للعمل الكامل تلقائيًا.</div></div></section>`;
}
function renderSafeView(view){
  const titles={catalog:'📦 البيانات الأساسية',pricing:'⚙️ التسعير',export:'📤 ERP'};
  app.innerHTML=`<section class="grid"><div class="card"><h2>${titles[view]||'النظام'}</h2><p>الشاشة متاحة، لكن التخزين المحلي لم يجهز بعد. انتظر لحظات أو استخدم إعادة المحاولة.</p><div class="toolbar"><button class="btn primary" id="retrySafe">إعادة المحاولة</button></div></div></section>`;
  document.getElementById('retrySafe').onclick=()=>location.reload();
}
async function resetLocalDb(){
  try{localStorage.clear();sessionStorage.clear();const req=indexedDB.deleteDatabase('slipperPricingDB_v14');req.onsuccess=()=>location.reload();req.onerror=()=>location.reload();req.onblocked=()=>{alert('أغلق أي تبويب آخر للنظام ثم اضغط موافق.');location.reload()}}catch(e){location.reload()}
}
async function boot(){
  renderSafeFallback();
  const timeout=new Promise((_,rej)=>setTimeout(()=>rej(new Error('انتهت مهلة تهيئة قاعدة البيانات المحلية (5 ثوانٍ).')),5000));
  try{
    await Promise.race([load(),timeout]);
    dbReady=true;bootError=null;renderDbStatus();
    await render();
  }catch(e){
    bootError=e;dbReady=false;console.error('Startup error:',e);renderSafeFallback();
    if(window.__showFatalError)window.__showFatalError('فشل تشغيل قاعدة البيانات المحلية عند الإقلاع: '+(e&&e.message||e));
  }
  // Retry once in the background after a short delay; never block the UI.
  if(!dbReady){setTimeout(async()=>{try{await load();dbReady=true;bootError=null;renderDbStatus();await render()}catch(e){bootError=e;renderSafeFallback();if(window.__showFatalError)window.__showFatalError('فشلت المحاولة الثانية لتشغيل قاعدة البيانات: '+(e&&e.message||e))}},2500)}
}
boot();
addEventListener('error',e=>{if(e?.error)console.error('Global error',e.error)});
addEventListener('unhandledrejection',e=>console.error('Unhandled promise',e.reason));
if('serviceWorker' in navigator){
  window.addEventListener('load',async()=>{
    try{
      const regs=await navigator.serviceWorker.getRegistrations();
      for(const r of regs){try{await r.unregister()}catch{}}
      const reg=await navigator.serviceWorker.register('./sw.js?v=1.3.2',{updateViaCache:'none'});
      await reg.update().catch(()=>{});
    }catch(e){console.warn('Service worker setup skipped',e)}
  });
}
